/**
 * Onboard Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CertificationCertificateCertificationCategory } from './certificationCertificateCertificationCategory';


export interface InlineResponse200 { 
    certificationId?: number;
    groupId?: string;
    name?: string;
    description?: string;
    validityPeriod?: number;
    requiresExpiryDate?: boolean;
    matrixCertification?: boolean;
    listOrder?: number;
    certificationCategoryId?: number;
    trainingCourseLength?: number;
    isCoreMobilisation?: boolean;
    trainingCost?: number;
    timeStamp?: string;
    certificationCategory?: CertificationCertificateCertificationCategory;
}
